import type { MikrotikDevice, VpnProfile } from "@shared/schema";

// Generate a standalone MikroTik script from VPN profile only (for VPN Tunnels page)
export function generateVpnTunnelScript(vpnProfile: VpnProfile): string {
  const ovpnConfig = vpnProfile.ovpnConfig;
  const remoteMatch = ovpnConfig.match(/remote\s+(\S+)\s+(\d+)/);
  const protoMatch = ovpnConfig.match(/proto\s+(tcp|udp)/i);

  const vpnServer = remoteMatch ? remoteMatch[1] : "<YOUR_VPN_SERVER>";
  const vpnPort = remoteMatch ? remoteMatch[2] : "1194";
  const vpnProto = protoMatch ? protoMatch[1].toLowerCase() : "udp";
  const sanitizedName = vpnProfile.name.replace(/[^a-zA-Z0-9_-]/g, "_");

  return `# ================================
# MikroTik OpenVPN Client Script
# Generated by OLT Management System
# VPN Tunnel: ${sanitizedName}
# Generated: ${new Date().toISOString()}
# ================================

# IMPORTANT: Review and adjust settings before running!
# This script configures your MikroTik router as an OpenVPN client
# to connect to the central OLT management VPN server.
# 
# SECURITY NOTE: You MUST replace <VPN_USERNAME> and <VPN_PASSWORD>
# with your actual VPN credentials before running this script.

# ================================
# OpenVPN Client Configuration
# ================================
# VPN Server: ${vpnServer}
# VPN Port: ${vpnPort}
# Protocol: ${vpnProto}

# Create OpenVPN client interface
/interface ovpn-client add name=ovpn-${sanitizedName} connect-to=${vpnServer} port=${vpnPort} mode=ip protocol=${vpnProto} user=<VPN_USERNAME> password=<VPN_PASSWORD> certificate=none auth=sha1 cipher=aes256 add-default-route=no profile=default-encryption comment="OLT Management VPN - ${vpnProfile.name}"

# Wait for interface to come up
:delay 5s

# ================================
# Routes for OLT Management
# ================================
# Add route to management network via VPN tunnel
/ip route add dst-address=10.0.0.0/8 gateway=ovpn-${sanitizedName} comment="OLT Management Network via VPN"

# ================================
# Firewall Rules for VPN
# ================================

# Allow established connections
/ip firewall filter add chain=input connection-state=established,related action=accept comment="Accept established connections"

# Allow OpenVPN traffic
/ip firewall filter add chain=input protocol=${vpnProto} dst-port=${vpnPort} action=accept comment="Allow OpenVPN ${vpnProto.toUpperCase()}"

# Allow management traffic from VPN network
/ip firewall filter add chain=input src-address=10.0.0.0/8 protocol=tcp dst-port=8728 action=accept comment="Allow API from VPN"
/ip firewall filter add chain=input src-address=10.0.0.0/8 protocol=tcp dst-port=22 action=accept comment="Allow SSH from VPN"

# ================================
# Logging
# ================================
/system logging add topics=ovpn action=memory comment="Log OpenVPN events"

# ================================
# Scheduler for VPN Health Check
# ================================
/system scheduler add name=vpn-health-${sanitizedName} interval=5m on-event="/interface ovpn-client monitor ovpn-${sanitizedName} once" comment="Monitor VPN connection status"

# ================================
# Script Complete
# ================================
:put "MikroTik VPN client script completed successfully!"
:put "VPN Tunnel: ${vpnProfile.name}"
:put ""
:put "Next steps:"
:put "1. Replace <VPN_USERNAME> and <VPN_PASSWORD> with actual credentials"
:put "2. Verify OpenVPN connection: /interface ovpn-client print"
:put "3. Check routes: /ip route print"
:put "4. Test connectivity to OLT management server"
`;
}

export function generateOnboardingScript(
  device: MikrotikDevice,
  vpnProfile?: VpnProfile | null
): string {
  let vpnConfig = "";
  let vpnPort = "1194";

  if (vpnProfile) {
    const ovpnConfig = vpnProfile.ovpnConfig;
    const remoteMatch = ovpnConfig.match(/remote\s+(\S+)\s+(\d+)/);
    const protoMatch = ovpnConfig.match(/proto\s+(tcp|udp)/i);

    const vpnServer = remoteMatch ? remoteMatch[1] : "<YOUR_VPN_SERVER>";
    vpnPort = remoteMatch ? remoteMatch[2] : "1194";
    const vpnProto = protoMatch ? protoMatch[1].toLowerCase() : "udp";

    vpnConfig = `
# ================================
# OpenVPN Client Configuration
# ================================
# IMPORTANT: Replace <VPN_USERNAME> and <VPN_PASSWORD> with actual credentials!

# Create OpenVPN client interface
/interface ovpn-client add name=ovpn-olt-management connect-to=${vpnServer} port=${vpnPort} mode=ip protocol=${vpnProto} user=<VPN_USERNAME> password=<VPN_PASSWORD> certificate=none auth=sha1 cipher=aes256 add-default-route=no profile=default-encryption comment="OLT Management VPN"

# Wait for interface to come up
:delay 5s

# Add route to management network via VPN tunnel
/ip route add dst-address=10.0.0.0/8 gateway=ovpn-olt-management comment="OLT Management Network via VPN"
`;
  }

  const sanitizedName = device.name.replace(/[^a-zA-Z0-9_-]/g, "_");

  return `# ================================
# MikroTik Onboarding Script
# Generated by OLT Management System
# Device: ${sanitizedName}
# Site: ${device.siteName || "N/A"}
# Generated: ${new Date().toISOString()}
# ================================

# IMPORTANT: Review and adjust settings before running!
# This script configures your MikroTik router as an OpenVPN client
# to connect to the central OLT management VPN server.
# 
# SECURITY NOTE: You MUST replace <VPN_USERNAME> and <VPN_PASSWORD>
# with your actual VPN credentials before running this script.

# ================================
# System Identity
# ================================
/system identity set name=${sanitizedName}

# ================================
# Basic Security Hardening
# ================================

# Disable unused services
/ip service disable telnet,ftp,www,api-ssl

# Enable API for OLT Management System access
/ip service set api address=0.0.0.0/0 port=${device.apiPort || 8728}

# Configure SSH (recommended for manual access)
/ip service set ssh port=22 address=0.0.0.0/0
${vpnConfig}

# ================================
# Firewall Rules for VPN
# ================================

# Allow established connections
/ip firewall filter add chain=input connection-state=established,related action=accept comment="Accept established connections"

# Allow OpenVPN traffic on configured port
/ip firewall filter add chain=input protocol=udp dst-port=${vpnPort} action=accept comment="Allow OpenVPN UDP"
/ip firewall filter add chain=input protocol=tcp dst-port=${vpnPort} action=accept comment="Allow OpenVPN TCP"

# Allow API access from VPN network
/ip firewall filter add chain=input src-address=10.0.0.0/8 protocol=tcp dst-port=${device.apiPort || 8728} action=accept comment="Allow API from VPN"

# ================================
# Logging
# ================================
/system logging add topics=ovpn action=memory comment="Log OpenVPN events"

# ================================
# Scheduler for VPN Health Check
# ================================
/system scheduler add name=vpn-health-check interval=5m on-event="/interface ovpn-client monitor ovpn-olt-management once" comment="Monitor VPN connection status"

# ================================
# Script Complete
# ================================
:put "MikroTik onboarding script completed successfully!"
:put "Device: ${sanitizedName}"
:put "VPN Tunnel IP: ${device.vpnTunnelIp || "Assigned by VPN server"}"
:put ""
:put "Next steps:"
:put "1. Replace <VPN_USERNAME> and <VPN_PASSWORD> with actual credentials"
:put "2. Verify OpenVPN connection: /interface ovpn-client print"
:put "3. Check routes: /ip route print"
:put "4. Test connectivity to OLT management server"
`;
}
