import type { VpnProfile } from "@shared/schema";

interface VpsFirewallOptions {
  vpnInterface?: string;
  vpnSubnet?: string;
}

export function generateVpsFirewallScript(
  vpnProfile: VpnProfile, 
  options: VpsFirewallOptions = {}
): string {
  const sanitizedName = vpnProfile.name.replace(/[^a-zA-Z0-9_-]/g, "_");
  const vpnInterface = options.vpnInterface || "tun0";
  const vpnSubnet = options.vpnSubnet || "10.8.0.0/24";
  
  const tr069Ips = vpnProfile.tr069Ips || [];
  const managementIps = vpnProfile.managementIps || [];
  const allIps = [...tr069Ips, ...managementIps];

  const iptablesRules = allIps.map(ip => {
    const addr = ip.includes('/') ? ip : `${ip}/32`;
    return `iptables -A FORWARD -i ${vpnInterface} -d ${addr} -j ACCEPT
iptables -A FORWARD -o ${vpnInterface} -s ${addr} -j ACCEPT`;
  }).join('\n');

  const natRules = allIps.map(ip => {
    const addr = ip.includes('/') ? ip : `${ip}/32`;
    return `iptables -t nat -A POSTROUTING -s ${vpnSubnet} -d ${addr} -o eth0 -j MASQUERADE`;
  }).join('\n');

  const routeCommands = allIps.map(ip => {
    const addr = ip.includes('/') ? ip : `${ip}/32`;
    return `ip route add ${addr} dev ${vpnInterface} 2>/dev/null || true`;
  }).join('\n');

  const ipsetCommands = allIps.map(ip => {
    const addr = ip.includes('/') ? ip : ip;
    return `ipset add vpn_allowed_${sanitizedName} ${addr} 2>/dev/null || true`;
  }).join('\n');

  return `#!/bin/bash
# ================================
# VPS OpenVPN Server Firewall Rules
# Generated by OLT Management System
# VPN Tunnel: ${vpnProfile.name}
# Generated: ${new Date().toISOString()}
# ================================

# This script configures iptables rules on the VPS (OpenVPN Server)
# to allow traffic routing between VPN clients and managed networks.

# Configuration
VPN_INTERFACE="${vpnInterface}"
VPN_SUBNET="${vpnSubnet}"
TUNNEL_NAME="${sanitizedName}"

echo "Configuring VPS firewall for VPN tunnel: ${vpnProfile.name}"
echo "VPN Interface: $VPN_INTERFACE"
echo "VPN Subnet: $VPN_SUBNET"

# ================================
# Enable IP Forwarding
# ================================
echo "Enabling IP forwarding..."
echo 1 > /proc/sys/net/ipv4/ip_forward

# Make it persistent
grep -q "net.ipv4.ip_forward" /etc/sysctl.conf || echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

# ================================
# Create IPSet for allowed networks (optional, for efficient matching)
# ================================
echo "Creating IPSet for VPN allowed networks..."
ipset create vpn_allowed_${sanitizedName} hash:net 2>/dev/null || ipset flush vpn_allowed_${sanitizedName}

# TR-069 Server IPs: ${tr069Ips.join(', ') || 'None configured'}
# OLT Management IPs: ${managementIps.join(', ') || 'None configured'}

${ipsetCommands || '# No networks configured'}

# ================================
# Clean up previous rules (if any)
# ================================
echo "Cleaning up previous firewall rules..."

# Remove old rules with our comment marker
iptables -S | grep "VPN-${sanitizedName}" | while read rule; do
  iptables \${rule/-A/-D} 2>/dev/null || true
done

iptables -t nat -S | grep "VPN-${sanitizedName}" | while read rule; do
  iptables -t nat \${rule/-A/-D} 2>/dev/null || true
done

# ================================
# FORWARD Chain Rules
# ================================
echo "Configuring FORWARD chain..."

# Allow forwarding for established connections
iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment "VPN-${sanitizedName}-established"

# Allow forwarding from VPN to managed networks
${iptablesRules || '# No forward rules configured'}

# ================================
# NAT / Masquerade Rules
# ================================
echo "Configuring NAT rules..."

# Masquerade VPN traffic going to managed networks
${natRules || '# No NAT rules configured'}

# General masquerade for VPN subnet
iptables -t nat -A POSTROUTING -s ${vpnSubnet} -o eth0 -j MASQUERADE -m comment --comment "VPN-${sanitizedName}-masq"

# ================================
# INPUT Chain Rules (for VPN server itself)
# ================================
echo "Configuring INPUT chain..."

# Allow OpenVPN connections
iptables -A INPUT -p udp --dport 1194 -j ACCEPT -m comment --comment "VPN-${sanitizedName}-openvpn-udp"
iptables -A INPUT -p tcp --dport 1194 -j ACCEPT -m comment --comment "VPN-${sanitizedName}-openvpn-tcp"

# Allow traffic from VPN interface
iptables -A INPUT -i $VPN_INTERFACE -j ACCEPT -m comment --comment "VPN-${sanitizedName}-input"

# ================================
# Static Routes (if needed)
# ================================
echo "Adding static routes..."

${routeCommands || '# No static routes configured'}

# ================================
# Save Rules (Debian/Ubuntu)
# ================================
echo "Saving iptables rules..."

if command -v netfilter-persistent &> /dev/null; then
  netfilter-persistent save
elif command -v iptables-save &> /dev/null; then
  iptables-save > /etc/iptables/rules.v4 2>/dev/null || iptables-save > /etc/iptables.rules
fi

# ================================
# Summary
# ================================
echo ""
echo "========================================="
echo "VPS Firewall Configuration Complete!"
echo "========================================="
echo "VPN Tunnel: ${vpnProfile.name}"
echo "VPN Interface: $VPN_INTERFACE"
echo "VPN Subnet: $VPN_SUBNET"
echo ""
echo "Allowed Networks:"
${allIps.map(ip => `echo "  - ${ip}"`).join('\n') || 'echo "  None configured"'}
echo ""
echo "Verification commands:"
echo "  iptables -L FORWARD -n -v"
echo "  iptables -t nat -L POSTROUTING -n -v"
echo "  ip route show"
echo "========================================="
`;
}

export function generateVpsFirewallCleanupScript(vpnProfile: VpnProfile): string {
  const sanitizedName = vpnProfile.name.replace(/[^a-zA-Z0-9_-]/g, "_");

  return `#!/bin/bash
# ================================
# VPS Firewall Cleanup Script
# VPN Tunnel: ${vpnProfile.name}
# ================================

echo "Removing firewall rules for VPN tunnel: ${vpnProfile.name}"

# Remove all rules with our comment marker
iptables -S | grep "VPN-${sanitizedName}" | while read rule; do
  iptables \${rule/-A/-D} 2>/dev/null || true
done

iptables -t nat -S | grep "VPN-${sanitizedName}" | while read rule; do
  iptables -t nat \${rule/-A/-D} 2>/dev/null || true
done

# Remove IPSet
ipset destroy vpn_allowed_${sanitizedName} 2>/dev/null || true

echo "Cleanup complete for: ${vpnProfile.name}"
`;
}
